CREATE TABLE PRODUTO (
    COD_PRODUTO VARCHAR(10) PRIMARY KEY,
    DES_PRODUTO VARCHAR(100) NOT NULL,
    STA_STATUS CHAR(1) NOT NULL
);

-- Tabela PRODUTO_COSIF
CREATE TABLE PRODUTO_COSIF (
    ID INT PRIMARY KEY,
    COD_PRODUTO VARCHAR(10) NOT NULL,
    COD_COSIF VARCHAR(10) NOT NULL,
    COD_CLASSIFICACAO VARCHAR(10) NOT NULL,
    STA_STATUS CHAR(1) NOT NULL,
    CONSTRAINT FK_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);

-- Tabela MOVIMENTO_MANUAL
CREATE TABLE MOVIMENTO_MANUAL (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DAT_MES INT NOT NULL,
    DAT_ANO INT NOT NULL,
    NUM_LANCAMENTO INT,
    COD_PRODUTO VARCHAR(10) NOT NULL,
    DAT_MOVIMENTO TIMESTAMP,
    VAL_VALOR DECIMAL(15,2) NOT NULL,
    COD_COSIF VARCHAR(10) NOT NULL,
    DES_DESCRICAO VARCHAR(255),
    COD_USUARIO VARCHAR(255),
    STA_STATUS CHAR(1),
    CONSTRAINT FK_MOV_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO)
);
