-- Inserindo produtos
INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
SELECT 'P001', 'Produto A', 'A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO WHERE COD_PRODUTO = 'P001');

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
SELECT 'P002', 'Produto B', 'A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO WHERE COD_PRODUTO = 'P002');

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
SELECT 'P003', 'Produto C', 'A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO WHERE COD_PRODUTO = 'P003');

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
SELECT 'P004', 'Produto D', 'A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO WHERE COD_PRODUTO = 'P004');

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
SELECT 'P005', 'Produto E', 'A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO WHERE COD_PRODUTO = 'P005');

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
SELECT 'P006', 'Produto F', 'A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO WHERE COD_PRODUTO = 'P006');

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
SELECT 'P007', 'Produto G', 'A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO WHERE COD_PRODUTO = 'P007');

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
SELECT 'P008', 'Produto H', 'A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO WHERE COD_PRODUTO = 'P008');

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
SELECT 'P009', 'Produto I', 'A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO WHERE COD_PRODUTO = 'P009');

INSERT INTO PRODUTO (COD_PRODUTO, DES_PRODUTO, STA_STATUS)
SELECT 'P010', 'Produto J', 'A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO WHERE COD_PRODUTO = 'P010');

-- Inserindo PRODUTO_COSIF correspondentes
INSERT INTO PRODUTO_COSIF (ID, COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
SELECT 1, 'P001', 'C001', 'CL1','A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO_COSIF WHERE ID = 1);

INSERT INTO PRODUTO_COSIF (ID, COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
SELECT 2, 'P002', 'C002', 'CL2','A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO_COSIF WHERE ID = 2);

INSERT INTO PRODUTO_COSIF (ID, COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
SELECT 3, 'P003', 'C003', 'CL1','A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO_COSIF WHERE ID = 3);

INSERT INTO PRODUTO_COSIF (ID, COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
SELECT 4, 'P004', 'C004', 'CL2','A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO_COSIF WHERE ID = 4);

INSERT INTO PRODUTO_COSIF (ID, COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
SELECT 5, 'P005', 'C005', 'CL1','A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO_COSIF WHERE ID = 5);

INSERT INTO PRODUTO_COSIF (ID, COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
SELECT 6, 'P006', 'C006', 'CL2','A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO_COSIF WHERE ID = 6);

INSERT INTO PRODUTO_COSIF (ID, COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
SELECT 7, 'P007', 'C007', 'CL1','A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO_COSIF WHERE ID = 7);

INSERT INTO PRODUTO_COSIF (ID, COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
SELECT 8, 'P008', 'C008', 'CL2','A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO_COSIF WHERE ID = 8);

INSERT INTO PRODUTO_COSIF (ID, COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
SELECT 9, 'P009', 'C009', 'CL1','A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO_COSIF WHERE ID = 9);

INSERT INTO PRODUTO_COSIF (ID, COD_PRODUTO, COD_COSIF, COD_CLASSIFICACAO, STA_STATUS)
SELECT 10, 'P010', 'C010', 'CL2','A' WHERE NOT EXISTS (SELECT 1 FROM PRODUTO_COSIF WHERE ID = 10);
